### PR TITLE
Initial Beachfront Adapter

### PR DESCRIPTION
**Pull request by jsalis**
Hi, I'm submitting the adapter for review.

Test Ad Slot Configuration
```javascript
{
  "appId": "3b16770b-17af-4d22-daff-9606bdf2c9c3",
  "bidfloor": 0.01,
  "sizes": [[300, 250]]
}
```

### CODE REVIEW

**Comment by ix-certification** [comment]
hi @jsalis 

After doing a quick round checks we found the following issue which is attributing to some failed test cases: The price in getValidResponse should be "2.00" as highlight [here](https://knowledgebase.indexexchange.com/display/ADAPTER/Test+Case+Functions). This the expected price to be set for the ad rendering test cases to work.

**Comment by jsalis** [comment]
@ix-certification 
Thanks. I fixed the price and the tests are passing now.

**Comment by ix-certification** [comment]
Thank @jsalis. We can confirm that all the tests are passing now as well. One last item before we can start reviewing the code, can we also update the files documentation.md and changes.md?

**Comment by jsalis** [comment]
@ix-certification 
I updated the documentation.

**Comment by jsalis** [comment]
@ix-certification 
Hi, have you had a chance to review the code?

**Comment by ix-certification** [comment]
Thanks, @jsalis , code has been reviewed and merged.

**Pull request merged**
